"""empty message

Revision ID: 207d83f95af7
Revises: a4afcf57535c
Create Date: 2024-12-26 22:05:51.578581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207d83f95af7'
down_revision = 'a4afcf57535c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
